packages:
  - "."

allowBuilds:
  '@prisma/engines': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - argon2
  - prisma
