-- Legacy feature flags are no longer seeded for seller/admin UX.
-- Product defaults now live in src/lib/config/runtime-controls.ts.
-- Existing rows can remain in already-provisioned dev databases; runtime code no longer depends on them.
