import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("mailbox sync reconnects orphan Gmail links to RT conversations", () => {
  const source = readFileSync("src/lib/mailboxes/sync.ts", "utf8");

  assert.match(source, /findMailgateIdentity/);
  assert.match(source, /RECENT_ORPHAN_BACKFILL_LIMIT.*0/);
  assert.match(source, /ORPHAN_BACKFILL_FETCH_BATCH_SIZE.*100/);
  assert.match(source, /function backfillRecentOrphanLinks/);
  assert.match(source, /parseEmailIdentity/);
  assert.match(source, /fetchInboxByUids/);
  assert.match(source, /index \+= ORPHAN_BACKFILL_FETCH_BATCH_SIZE/);
  assert.match(source, /isUnread:\s*gmailUnread/);
  assert.match(source, /senderEmail:\s*senderEmail/);
  assert.match(source, /conversationId:\s*null/);
  assert.match(source, /type:\s*"INBOX"/);
  assert.match(source, /Number\(right\.uid - left\.uid\)/);
  assert.match(source, /committedUid && committedUid > lastCommittedUid/);
  assert.match(source, /const observedNames = \[\.\.\.new Set\(\["inbox", \.\.\.message\.labels\.map\(normalizeObservedLabel\)\]\)\]/);
  assert.match(source, /scanSent/);
  assert.match(source, /\.\.\.scan\.messages, \.\.\.sentScan\.messages/);
  assert.match(source, /function isOutboundGmailMessage/);
  assert.match(source, /return !message\.flags\.includes\("\\\\Seen"\) && !isOutboundGmailMessage\(message\)/);
  assert.match(source, /message\.labels\.map\(normalizeObservedLabel\)\.includes\("sent"\)/);
  assert.match(source, /const direction = isOutboundGmailMessage\(message\) \? "OUTBOUND" : "INBOUND"/);
  assert.match(source, /link\.direction !== direction && direction === "OUTBOUND"/);
  assert.match(source, /adminReplyMetricInputs\.push/);
  assert.match(source, /void input\.adminReplyMetricInputs/);
  assert.match(source, /articleCount: messageCount/);
  assert.match(source, /mailboxResponseMetric\.upsert/);
  assert.match(source, /const inbound = links\.find\(\(link\) => link\.direction === "INBOUND"\)/);
  assert.match(source, /const latestReply = responseStartedAt/);
  assert.match(source, /durationMsBetween\(responseStartedAt, latestAdminReplyAt\)/);
  assert.match(source, /gmailOnly \+= 1/);
  assert.match(source, /return message\.uid/);
  assert.match(source, /lastCommittedUid:\s*effectiveLastCommittedUid/);
  assert.match(source, /runtime scans are bounded batches, not full Inbox snapshots/);
  assert.doesNotMatch(source, /conversationId:\s*\{\s*notIn:\s*inboxIds\s*\}/);
  assert.match(source, /GMAIL_RATE_LIMIT_ERROR_CODE/);
  assert.match(source, /isGmailRateLimitError/);
  assert.match(source, /code === GMAIL_RATE_LIMIT_ERROR_CODE/);
  assert.match(source, /MAILBOX_BACKFILL_CHUNK_SIZE/);
  assert.match(source, /oldestFirst:\s*true/);
  assert.match(source, /folder === "SENT"/);
  assert.match(source, /backfillNext/);
  assert.doesNotMatch(source, /response_metric_skipped/);
  assert.doesNotMatch(source, /limit:\s*null/);
  assert.doesNotMatch(source, /lastCommittedUid:\s*BigInt\(0\),\n\s*\}\);\n\s*if \(/);
});
